config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end
  
  root to: 'registrations#new'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  
  validates :user, presence: true
  validates :content, presence: true, length: { in: 1..140}
  
  default_scope -> { order(created_at: :desc) }
  
  def favorited_by? user
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :require_login, except: [:index]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end
  
  def timeline
    @tweets = Tweet.eager_load(user: :inverse_follows).where(follows: { follower_id: current_user.id })
    @tweet  = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "ツイートを送信しました" }
        format.json { render :show, status: :created, location: @tweet }
      else
        @tweets = Tweet.all
        format.html { render :index }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "ツイートを更新しました" }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "ツイートを削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for @tweet do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:" %>
      </h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/tweets/_panel.html.erb
<% if logged_in? %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to user_path(current_user), class: "user" do %>
        <span class="user-name">
          <%= render_user_screen_name current_user %>
        </span>
        <span class="user-id">
          <%= current_user.name %>
        </span>
      <% end %>
      <div class="user-activity">
        <div class="row">
          <div class="col-xs-4 tweets-num">
            <div class="text">
              つぶやき
            </div>
            <div class="num">
              <%= link_to current_user.tweets.count, user_path(current_user) %>
            </div>
          </div>
          <div class="col-xs-4 follow-num">
            <div class="text">
              フォロー
            </div>
            <div class="num">
              <%= link_to current_user.inverse_followers.count, follows_user_path(current_user) %>
            </div>
          </div>
          <div class="col-xs-4 follower-num">
            <div class="text">
              フォロワー
            </div>
            <div class="num">
              <%= link_to current_user.followers.count, followers_user_path(current_user) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% @tweet.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
  <%= form_for @tweet do |f| %>
    <div class="form-group">
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <%= f.submit "つぶやく", class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>
<%= render 'form' %>
<%= link_to 'Show', @tweet %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div id="tweets-content">
  <div class="container">
    <div class="row">
      <div class="col-4 left-content">
        <%= render partial: "panel" %>
      </div>
      <div class="col-8 right-content">
        <% if notice %>
          <div class="alert alert-info">
            <%= notice %>
          </div>
        <% end %>
        <div class="list-group">
          <div class="list-group-item">
            <div class="btn-group">
              <%= link_to "全てのつぶやき", tweets_path, class: "active btn btn-primary" %>
              <%= link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default" %>
            </div>
          </div>
          <%= render partial: "users/tweet", collection: @tweets %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>
<%= render 'form' %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>User:</b>
  <%= @tweet.user_id %>
</p>
<p>
  <b>Content:</b>
  <%= @tweet.content %>
</p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/timeline.html.erb
<div id="tweets-content">
  <div class="container">
    <div class="row">
      <div class="col-4 left-content">
        <%= render partial: "panel" %>
      </div>
      <div class="col-8 right-content">
        <% if notice %>
          <div class="alert alert-info">
            <%= notice %>
          </div>
        <% end %>
        <div class="list-group">
          <div class="list-group-item">
            <div class="btn-group">
              <%= link_to "全てのつぶやき", tweets_path, class: "active btn btn-primary" %>
              <%= link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default" %>
            </div>
          </div>
          <%= render partial: "users/tweet", collection: @tweets %>
        </div>
      </div>
    </div>
  </div>
</div>