config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end
  
  root to: 'registrations#new'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :follows, foreign_key: :follower_id
  has_many :inverse_followers, through: :follows
  has_many :inverse_follows, foreign_key: :inverse_follower_id, class_name: Follow
  has_many :followers, through: :inverse_follows
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
  validates :screen_name, length: { maximum: 140 }
  validates :bio, length: { maximum: 200  }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password
  
  def followed_by? user
    inverse_follows.where(follower_id: user.id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end
  
  def favorites
    @user = User.find(params[:id])
  end
  
  def follows
    @user = User.find(params[:id])
  end
 
  def followers
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def render_user_screen_name user
    if user.screen_name.blank?
      user.name
    else
      user.screen_name
    end
  end
end

app/views/users/_header.html.erb
<div class="user-info">
  <% if notice %>
    <div class="alert alert-info">
      <%= notice %>
    </div>
  <% end %>
  <span class="user-name">
    <%= render_user_screen_name(@user) %>
  </span>
  <span class="user-id">
    <%= @user.name %>
  </span>
  <div class="bio">
    <%= @user.bio %>
  </div>
</div>
<ul class="nav nav-tabs nav-justified">
  <li class="<%= action_name == "show" ? "active" : nil %>">
    <%= link_to user_path(@user) do %>
      <div class="text">
        つぶやき
      </div>
      <div class="num">
        <%= @user.tweets.count %>
      </div>
    <% end %>
  </li>
  <li class="<%= action_name == "follows" ? "active" : nil %>">
    <%= link_to follows_user_path(@user) do %>
      <div class="text">
        フォロー
      </div>
      <div class="num">
        <%= @user.inverse_followers.count %>
      </div>
    <% end %>
  </li>
  <li class="<%= action_name == "followers" ? "active" : nil %>">
    <%= link_to followers_user_path(@user) do %>
      <div class="text">
        フォロワー
      </div>
      <div class="num">
        <%= @user.followers.count %>
      </div>
    <% end %>
  </li>
  <li class="<%= action_name == "favorites" ? "active" : nil %>">
    <%= link_to favorites_user_path(@user) do %>
      <div class="text">
        お気に入り
      </div>
      <div class="num">
        <%= @user.favorites.count %>
      </div>
    <% end %>
  </li>
</ul>

app/views/users/_tweet.html.erb
<%= div_for tweet, class: "list-group-item" do |t| %>
  <h4 class="user">
    <span class="user-name">
      <%= link_to t.user.name, user_path(t.user) %>
    </span>
    <span class="user-id">
      <%= t.user.name %>
    </span>
    <span class="time pull-right">
      <%= distance_of_time_in_words_to_now(t.created_at) %>
    </span>
    <div class="clear"></div>
  </h4>
  <div class="tweet-content">
    <p>
      <%= t.content %>
    </p>
    <div class="content-footer">
      <% if t.favorited_by? current_user %>
        <%= link_to "お気に入りの解除", tweet_favorites_path(t), method: :delete %>
      <% else %>
        <%= link_to "お気に入りに登録", tweet_favorites_path(t), method: :post %>
      <% end %>
      
      <% if t.user.followed_by? current_user %>
        <%= link_to "フォロー解除", user_follows_path(t.user), method: :delete %>
      <% else %>
        <%= link_to "フォロー", user_follows_path(t.user), method: :post %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= div_for user, class: "list-group-item" do |u| %>
  <h4 class="user">
    <span class="user-name">
      <%= link_to u.name, user_path(u) %>
    </span>
    <span class="user-id">
      <%= u.name %>
    </span>
  </h4>
  <div class="bio">
    <%= u.bio %>
  </div>
  <div class="follow-unfollow">
    <% if u.followed_by? current_user %>
      <%= link_to "フォロー解除", user_follows_path(u), method: :delete %>
    <% else %>
      <%= link_to "フォロー", user_follows_path(u), method: :post %>
    <% end %>
  </div>
<% end %>

app/views/users/favorites.html.erb
<div class="col" id="users-content">
  <%= render partial: "users/header" %>
  <div class="list-group">
    <% if @user.favorites.empty? %>
      <div class="list-group-item">
        まだお気に入りに登録されたツイートはありません
      </div>
    <% end %>
    <%= render partial: "users/tweet", collection: @user.favorites.map{|f| f.tweet} %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="col" id="users-content">
  <%= render partial: "users/header" %>
  <div class="list-group">
    <%= render @user.followers %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="col" id="users-content">
  <%= render partial: "users/header" %>
  <div class="list-group">
    <%= render @user.inverse_followers %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col" id="users-content">
      <div class="list-group">
        <div class="list-group-item user-list">
          <h2>ユーザー一覧</h2>
          <%= render partial: "users/user", collection: @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col" id="users-content">
  <%= render partial: "users/header" %>
  <div class="list-group">
    <% if @user.tweets.empty? %>
      <div class="list-group-item">
        まだツイートはありません
      </div>
    <% end %>
    <%= render partial: "users/tweet", collection: @user.tweets %>
  </div>
</div>