config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end
  
  root to: 'registrations#new'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params_user)
      redirect_to user_url(@user), notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end
  
  private
  
  def params_user
    params.require(:user).permit(:name, :screen_name, :bio)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<div class="container">
  <div id="settings-edit">
    <div class="row">
      <div class="col settings-content">
        <% @user.errors.each do |attr, message| %>
          <div class="alert alert-danger">
            <%= message %>
          </div>
        <% end %>
        <%= form_for @user, url: settings_path, method: :put do |f| %>
          <h2>設定</h2>
          <div class="form-body">
            <div class="form-group">
              <%= f.label :name, "ユーザーID", class: "control-label" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :screen_name, "表示名", class: "control-label" %>
              <%= f.text_field :screen_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :bio, "プロフィール(200文字)", class: "control-label" %>
              <%= f.text_area :bio, class: "form-control" %>
            </div>
            <%= f.submit "送信", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>