config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]
  
  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end
  
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end
  
  root to: 'registrations#new'
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to '#PortfolioApp', root_url, class: "navbar-brand" %>
    </div>
    <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "全ツイート一覧", tweets_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to "設定", edit_settings_path %></li>
        <li><%= link_to "ログアウト", sessions_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "会員登録", new_registrations_path %></li>
        <li><%= link_to "ログイン", new_sessions_path %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="application">
    <div>
      <%= render partial: "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/registrations.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body id="registrations">
    <%= yield %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body id="sessions">
    <%= yield %>
  </body>
</html>